common:
 namespace: todoapp
 environment: "Development"


todoapp:
  image:
    name: todoapp
    repository: ikulyk404/todoapp
    version: "4.0.1"
  resources:
    requests:
      memory: "256Mi"
      cpu: "150m"
    limits:
      memory: "256Mi"
      cpu: "150m"
  spec:
    replicas: "3"
    strategy:
      type: RollingUpdate
      rollingUpdate:
        maxSurge: 1
        maxUnavailable: 1
    affinity:
      nodeAffinity:
        preferredDuringSchedulingIgnoredDuringExecution:
        - weight: 1
          preference:
            matchExpressions:
            - key: app
              operator: In
              values:
              - kube2py
  serviceAccountName: secrets-reader
  hpa:
    enabled: false
    minReplicas: 2
    maxReplicas: 5
    cpu:
      averageUtilization: 70
    memory:
      averageUtilization: 70
  pv:
    capacity:
      storage: 1Gi
  pvc:
    requests:
      storage: 1Gi
  secrets:
    data:
      SECRET_KEY: "@e2(yx)v&tgh3_s=0yja-i!dpebxsz^dg47x)-k&kq_3zf*9e*"
      DB_NAME: "app_db"
      DB_USER: "app_user"
      DB_PASSWORD: "1234"
      DB_HOST: "mysql-0.mysql.mysql.svc.cluster.local"
  env:
    - name: PYTHONUNBUFFERED
      valueFrom:
        configMapKeyRef:
          name: app-config
          key: PYTHONUNBUFFERED
    - name: SECRET_KEY
      valueFrom:
        secretKeyRef:
          name: app-secret
          key: SECRET_KEY
    - name: DB_NAME
      valueFrom:
        secretKeyRef:
          name: app-secret
          key: DB_NAME
    - name: DB_USER
      valueFrom:
        secretKeyRef:
          name: app-secret
          key: DB_USER
    - name: DB_PASSWORD
      valueFrom:
        secretKeyRef:
          name: app-secret
          key: DB_PASSWORD
    - name: DB_HOST
      valueFrom:
        secretKeyRef:
          name: app-secret
          key: DB_HOST
